keys:
  - &users '':
      - &delusion age1kv9lld6yrtu3udyu083amzvd6zh64nxdg3a4m64nxxdfxc58ggdsgu5wxe
  - &hosts '':
      - &ember age14980r3x57qm9054r6rjzz0matdznr6r0z94gg4hzgshll0w0tyusfp62fd
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *delusion
          - *ember
